### PR TITLE
Fixing readme path

### PR DESCRIPTION
**Pull request by abaniuszewicz**
Fixing path for Markdig-readme.md on Markdig.Wpf.SampleAppCustomized that was causing System.IO.DirectoryNotFoundException throw

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
Actually it was done like this on purpose (see #33). But it is correct that the path is wrong since multi-targeting was added. It should have one more `../`.

**Comment by abaniuszewicz** [comment]
I see, seems like this works this way too. Should I apply the same path on other sample project, Markdig.Wpf.SampleApp?

**Comment by Kryptos-FR** [comment]
No. The other project shouldn't be changed.

Your last commit did an unexpected merge which is incorrect. Can you go back one commit before and force-push a new commit with only the changes? In general, you shouldn't create new commits (or new pull-requests) but amend the previous one (see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

**Comment by abaniuszewicz** [comment]
Thank you very much for the tips! Looks like it worked correctly with combination of `git reset` to original commit, adding my changes and `git push -f` once again. Seems like history was rewritten correctly.

Also, one more thing that bugs me - should this PR be pushed to `master` or `develop` branch? My original intention was to push this straight to `master` (like [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) recommends), but looks like I've branched out of `develop`. Should I change target branch to `develop` or maybe somehow change my parent branch?

**Comment by Kryptos-FR** [comment]
> Also, one more thing that bugs me - should this PR be pushed to master or develop branch?

I used `develop` from time to time to work on new stuff or test things. But `master` is the right one you should target. I forgot to synchronize the two, so I'll do it now.

**Pull request merged**
