### PR TITLE
Hyperlink improvements

### PR DESCRIPTION
**Pull request by jackgriffiths**
I've made some improvements to links and autolinks:

* Added a hyperlink style.
* Fixed the WPF autolink renderer - the autolinks weren't being displayed.
* For email autolinks, the URL of the hyperlink is now "mailto:" followed by the email address.

### CODE REVIEW

**Review by Kryptos-FR — APPROVED** [review]
LGTM. Thanks for the contribution.

I'll do some testing soon and merge it if everything is ok.

**Comment by Kryptos-FR** [comment]
Waiting for some inputs on https://github.com/lunet-io/markdig/issues/262.
Do email links work for you?

**Comment by jackgriffiths** [comment]
Yes, it parses `<test@example.com>` as an email autolink.

**Comment by Kryptos-FR** [comment]
I'll accept is as-is but wait for the answer on markdig issue before releasing a new package.
Thanks.

**Pull request merged**
