### PR TITLE
[Markdig.Wpf] Allow UriKind RelativeOrAbsolute in LinkInlineRenderer.cs

### PR DESCRIPTION
**Pull request by davidholsgrove**
Update example Documents directory to contain a local image (BenchmarkCPU) and have Markdig-readme.md use a relative link to the image file.

Prevents exception being thrown when using relative link;

> Exception thrown: 'System.UriFormatException' in System.dll
> An unhandled exception of type 'System.UriFormatException' occurred in System.dll
> Invalid URI: The format of the URI could not be determined.

> Unhandled Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
>    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>    at System.Uri..ctor(String uriString)
>    at Markdig.Renderers.Wpf.Inlines.LinkInlineRenderer.Write(WpfRenderer renderer, LinkInline link) in markdig.wpf\src\Markdig.Wpf\Renderers\Wpf\Inlines\LinkInlineRenderer.cs:line
34
>    at Markdig.Renderers.MarkdownObjectRenderer`2.Write(RendererBase renderer, MarkdownObject obj)
>    at Markdig.Renderers.RendererBase.Write[T](T obj)
>    at Markdig.Renderers.RendererBase.WriteChildren(ContainerInline containerInline)
>    at Markdig.Renderers.RendererBase.Write[T](T obj)
>    at Markdig.Renderers.WpfRenderer.WriteLeafInline(LeafBlock leafBlock) in markdig.wpf\src\Markdig.Wpf\Renderers\WpfRenderer.cs:line 82

### CODE REVIEW

**Comment by davidholsgrove** [comment]
Hi @Kryptos-FR,
I added an additional commit, which uses the https://github.com/XamlAnimatedGif/XamlAnimatedGif project to create ".gif" links as animated gifs instead of static bitmaps.

Happy to split out into separate PR if you'd prefer.

thanks for all your work on markdig.wpf - its awesome 👍 
thanks,
David

**Comment by Kryptos-FR** [comment]
Thanks.

I would rather have the animated gif in a separate pull-request. Ideally it should be an option/plugin to use it or not.

**Comment by Kryptos-FR** [comment]
Sorry I didn't have time recently to spend  on Markdig.Wpf. I'll extract (cherry-pick) your commit that fixes the URL and review later the rest of the PR.

Thanks again for the contribution.

**Comment by Kryptos-FR** [comment]
I'm closing this PR since the related changes have been merged already. Feel free to open a new one for the GIF part.

**Pull request closed without merging**
