### PR TITLE
multi-target to .net core 3

### PR DESCRIPTION
**Pull request by virzak**

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
Hi @virzak 

As I mentioned in #26, I am waiting for the official release before doing (or that case merging) any work related to .NET Core 3. I don't want to install any preview version of Visual Studio on my machine as I had some bad experience with it in the past.

Feel free to ping me after the official release, in case I forget.

**Comment by virzak** [comment]
@Kryptos-FR 

Will ping for sure.

I also don't have a preview version. It work perfectly fine in the latest stable version.
The other option is to use VS Code.

Totally understand if you want to wait.

**Comment by virzak** [comment]
VS 16.3 is out now

**Comment by Kryptos-FR** [comment]
Change was straightforward. Thanks for the contribution.

**Comment by virzak** [comment]
Could you please push this to nuget?

**Comment by Kryptos-FR** [comment]
Sure. Will do as soon as I can.
Thanks is for the reminder.

**Comment by virzak** [comment]
@Kryptos-FR Thanks so much!

**Comment by Kryptos-FR** [comment]
@virzak Sorry for the delay. It should be available now on nuget.

**Pull request merged**
